name: Deploy AWS SAM Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install AWS CLI
        run: |
          curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

      - name: Install SAM CLI
        run: |
          sudo pip3 install aws-sam-cli

      - name: Build and Deploy
        run: |
          sam build
          sam deploy --stack-name notes-backend --s3-bucket ${{ secrets.S3_DEPLOYMENT_BUCKET }} --region ${{ secrets.AWS_REGION }} --capabilities CAPABILITY_IAM
